runtime: nodejs
vm: true

env_variables:
  # --REQUIRED--
  DATABASE_URI: mongodb://admin:admin@ds135689.mlab.com:35689/wiibeast
  APP_ID: 4v3fI7R1Hrj2GJcHTjSeK6ynOCTmfI8rpXwO3i6J
  MASTER_KEY: Od2aQxXUkExNqduwIKpGkwHDIOofzlFNunmHxROh
  # --OPTIONAL--
  # FILE_KEY: <your-file-key>
  # PARSE_MOUNT: /parse
  # CLOUD_CODE_MAIN:  